---
spring:
  profiles: local, test

  h2.console:
    enabled: true
    path: /h2-console

  datasource:
    jdbcUrl: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;mode=MySQL;
    username: sa
    password:
    driverClassName: org.h2.Driver
    maximumPoolSize: 5
    minimumIdle: 5

  jpa:
    database: h2
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        show-sql: true
        format-sql: true
        use_sql_comments: true

---
spring:
  profiles: dev

  datasource:
    jdbcUrl:
    username:
    password:
    driverClassName: com.mysql.jdbc.Driver
    maximumPoolSize: 10
    minimumIdle: 10
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false

  jpa:
    database: mysql
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        show-sql: true
        format-sql: true
        use_sql_comments: true